#!/bin/bash

# shellcheck disable=SC1090,1091

NL=$'\n'
TAB=$'\t'
# unicode justification markers
LRM=$'\u200E'  # LEFT-TO-RIGHT MARK
RLM=$'\u200F'  # RIGHT-TO-LEFT MARK
WARNING_ICON=$'\u26A0'
RIGHT_PARENTHESES=$')\uFF09'

PUNCTUATION=(
    ':'
    '.'
    ','
    $'\uFE13'  # VERTICAL_COLON
    $'\uFE55'  # SMALL_COLON
    $'\uFF1A'  # FULL_WIDTH_COLON
    $'\u3002'  # IDEOGRAPHIC_FULL_STOP
    $'\uFE51'  # SMALL_IDEOGRAPHIC_COMMA
    $'\uFF64'  # HALFWIDTH_IDEOGRAPHIC_COMMA
    $'\u0964'  # DEVANAGARI_DANDA
    $'\u0903'  # DEVANAGARI_SIGN_VISARGA
    $'\u06D4'  # ARABIC_FULL_STOP
    $'\u060C'  # ARABIC_COMMA
    $'\u05C3'  # HEBREW_SOF_PASUQ
    $'\u0589'  # ARMENIAN_FULL_STOP
    $'\u055D'  # ARMENIAN_COMMA
    $'\u1362'  # ETHIOPIC_FULL_STOP
    $'\u1363'  # ETHIOPIC_COMMA
    $'\u1361'  # ETHIOPIC_WORDSPACE
    $'\uA789'  # MODIFIER_LETTER_COLON
    $'\u2236'  # RATIO_COLON
    $'\u205A'  # TWO_DOT_PUNCTUATION
    $'\uFF0C'  # FULLWIDTH_COMMA
    $'\u0F0D'  # TIBETAN_MARK_SHAD
    $'\u17D6'  # KHMER_SIGN_CAMNUC_PII_KUUH
    $'\u1038'  # MYANMAR_SIGN_VISARGA
    $'\uABEB'  # MEETEI_MAYEK_CHEIKHEI
)

NINES=(
    # Possibly version specific, Bash regex, as dependent on system regex,
    # appears to be blind to some unicode 9s in certain situations.
    # The following will be used to build a reges range of 9s:
    $'\u0669' $'\u06F9' $'\u07C9' $'\u096F' $'\u09EF' $'\u0A6F' $'\u0AEF'
    $'\u0B6F' $'\u0BEF' $'\u0C6F' $'\u0CEF' $'\u0D6F' $'\u0DEF' $'\u0E59'
    $'\u0ED9' $'\u0F29' $'\u0F32' $'\u1049' $'\u1099' $'\u1371' $'\u17E9'
    $'\u1819' $'\u194F' $'\u19D9' $'\u1A89' $'\u1A99' $'\u1B59' $'\u1BB9'
    $'\u1C49' $'\u1C59' $'\uA629' $'\uA6EE' $'\uA8D9' $'\uA909' $'\uA9D9'
    $'\uA9F9' $'\uAA59' $'\uABF9')

# regex range - alien characters that occur in some translations,
# e.g. Hebrew, and disrupt parsing for delimiters
ALIEN_CHARS="\'\\\"\\\\"

punct=${PUNCTUATION[*]}
punct=${punct// /}
nines=${NINES[*]}
nines=${nines// /}

# regex patterns applied to trans output
PATTERN_DIVISIONS="([^${RIGHT_PARENTHESES}]+)"
PATTERN_ELEMENTS="([0-9${nines}]+)[^${punct}]+[${punct}]+\s*-*\s*(.*)"

# default language
LANGUAGE="en"
LANGUAGE_DIRECTION="LTR"

trap "exit 1" TERM
export TOP_PID=$$

error_exit() {
    cmd_info="${TEXT_CMD_INFO//0/$2}: ${NL}${NL}$1${NL}${NL}"
    output_info="$TEXT_OUTPUT:${NL}${NL}$3"
    
    if zenity --text-info --title="$TITLE${NL}$WARNING_ICON $TEXT_ERROR" \
        --width=600 --height=500 \
        --cancel-label="${LRM}$ERROR_BTN_EXIT" \
        --ok-label="${LRM}$ERROR_BTN_RETRY" \
        2> /dev/null <<< "$cmd_info$output_info" ; then
        echo 1
    else
        kill -s TERM $TOP_PID
        echo 0
    fi
}

fail_exit() {
    zenity --text-info --title="$TITLE${NL}$WARNING_ICON $1" \
        --width=600 --height=500 --cancel-label="" <<< "$2"
    >&2 echo "$1:${NL}${NL}$2"
    kill -s TERM $TOP_PID
}

exec_command() {
    command="$1"
    status=1
    while (( status )); do
        output="$(eval "$command" 2>&1)"
        status=$?
        if (( status )); then
            >&2 echo "$output"
            status=$(error_exit "$command" "$status" "$output")
        else
            echo "$output"
        fi
    done
}

check_lang() {
    codes=$(trans --list-codes)
    for code in $codes ; do
        [[ "$code" == "$1" ]] && return
    done
    err_text="Invalid language code: $1"
    if ! zenity --question --title="$TITLE - Error" \
        --text="$err_text${NL}${NL}Do you wish to continue?" \
        --width=300 --icon="data-warning" --no-markup ; then
        kill -s TERM $TOP_PID
    fi
}

normalise_digits() {
    perl -CS -MUnicode::UCD=charinfo -pe '
        s/\p{Nd}/charinfo(ord($&))->{numeric}/ge'
}

rstrip() {
    echo "${1%"${1##*[![:space:]]}"}"
}

findall() {
    local input=$1
    local pattern=$2
    local -n matches=$3
    local countdown=$4

    (( countdown-- ))
    if [[ $input =~ $pattern ]] ; then
        # prevent infinite recursion if parsing fails
        if (( countdown >= -1 )) ; then
            matches+=( "${BASH_REMATCH[0]}" )
            findall "${input/${BASH_REMATCH[0]}/}" "$pattern" "$3" "$countdown"
        else
            return 1
        fi
    fi
}

translate() {
    local trans_input=$1
    local translation
    local lang=$2
    local -n divisions=$3
    local last_index_in=$4

    # translation parsing is geared for output from the google engine
    cmd="trans -b -4 -no-warn -e \"$ENGINE\" -4 en:$lang \"$trans_input\""
    translation="$(exec_command "$cmd")"
    # filter out known alien characters
    translation="${translation//[${ALIEN_CHARS}]/}"
    if ! findall "$translation" "${PATTERN_DIVISIONS}" divisions "$last_index_in" ; then
        err_msg1=$'This may be caused by alien characters that prevent parsing '
        err_msg2=$'of translated text for delimiters (see README.md).\n\n'
        err_msg3="Input:${NL}${NL}${trans_input}${NL}${NL}"
        err_msg4="Output:${NL}${NL}${translation}"
        fail_exit "Parsing error" "$err_msg1$err_msg2$err_msg3$err_msg4" 
    fi
    last_index_out=$(( ${#divisions[@]} - 1 ))
    if (( last_index_out < 0 )) ; then
        err_msg1=$'This may be caused by use of a language code unsupported '
        err_msg2=$'by Google, e.g. tlh-Latn (Klingon). Otherwise, it may be '
        err_msg3='due to a temporary translation engine or network error. '
        err_msg4=$'In this case, try restarting weather-now-menu.\n\n'
        err_msg5="Input:${NL}${NL}${trans_input}${NL}${NL}"
        err_msg6="Output:${NL}${NL}${translation}"
        fail_exit "Parsing error" \
            "$err_msg1$err_msg2$err_msg3$err_msg4$err_msg5$err_msg6" 
    fi
    last_match=${divisions[$last_index_out]}
    [[ "$last_match" =~ ^([[:space:]]|[[:punct:]])*$ ]] && \
        unset "divisions[$last_index_out]"
}

translate_locations() {
    local -n locations=$1
    local lang=$2
    local output_file=$3
    local prefix=$4
    local location
    local trans_input
    local -a trans_divs
    local translation

    for ((i=0; i < ${#locations[@]}; i++)); do
        location=${locations[$i]} 
        trans_input+="$i ( $prefix${location%:*} ). "
    done

    translate "$trans_input" "$lang" trans_divs $i
    echo "LOCATIONS_NATIVE=(" > "$output_file"

    for div in "${trans_divs[@]}" ; do
        div=$(rstrip "$div")
        [[ "$div" =~ $PATTERN_ELEMENTS ]]
        translation="${BASH_REMATCH[2]}"
        echo "${TAB}\"${translation}\"" >> "$output_file"
    done

    echo ")" >> "$output_file"
}

translate_labels() {
    local -n labels=$1
    local -n label_ids=$2
    local lang=$3
    local output_file=$4
    local prefix=$5
    local trans_input
    local -a trans_divs
    local translation

    for ((i=0; i < ${#labels[@]}; i++)); do
        trans_input+="$i ( $prefix${labels[$i]} ). "
    done

    translate "$trans_input" "$lang" trans_divs $i

    for (( i=0; i < ${#label_ids[@]}; i++ )) ; do
        div=$(rstrip "${trans_divs[$i]}")
        [[ $div =~ $PATTERN_ELEMENTS ]]
        translation="${BASH_REMATCH[2]}"
        [[ "$LANGUAGE_DIRECTION" == "LTR" ]] && translation="${translation^}"
        echo "${label_ids[$i]}=\"${translation}\"" >> "$output_file"
    done
}

translate_codes() {
    local lang=$2
    local output_file=$3
    local prefix=$4
    local trans_input
    local -a trans_divs
    local code
    local description

    for (( i=0; i < 100; i++ )) ; do
        if [[ ${CONDITIONS[${i}]} ]] ; then
            trans_input+="$i ( $prefix${CONDITIONS[${i}]} ). "
        fi
    done

    translate "$trans_input" "$lang" trans_divs ${#CONDITIONS[@]}
    echo "CONDITIONS_NATIVE=(" > "$output_file"

    for div in "${trans_divs[@]}" ; do
        div=$(rstrip "$div")
        [[ $div =~ $PATTERN_ELEMENTS ]]
        code=$(normalise_digits <<< "${BASH_REMATCH[1]}")
        description="${BASH_REMATCH[2]}"
        [[ "$LANGUAGE_DIRECTION" == "LTR" ]] && description="${description^}"
        echo "${TAB}[$code]=\"${description}\"" >> "$output_file"
    done

    echo ")" >> "$output_file"
}

translate_extra_parameters() {
    local -n params=$1
    local lang=$2
    local output_file=$3
    local prefix=$4
    local trans_input
    local -a trans_divs

    for ((i=0; i < ${#params[@]}; i++)); do
        p=${params[$i]}
        p="${p//_/ }"
        p="${p^}"
        trans_input+="$i ( $prefix$p ). "
    done

    translate "$trans_input" "$lang" trans_divs $i

    for div in "${trans_divs[@]}" ; do
        div=$(rstrip "$div")
        [[ $div =~ $PATTERN_ELEMENTS ]]
        i=$(normalise_digits <<< "${BASH_REMATCH[1]}")
        trans="${BASH_REMATCH[2]}"
        case "${params[i]}" in
            "cape" )
                k="CAPE"
                trans="$k" ;;
            "total_column_integrated_water_vapour" )
                k="TCWV"
                trans="$k" ;;
            *)
                typeset -u k="${params[i]}"
        esac
        [[ "$LANGUAGE_DIRECTION" == "LTR" ]] && trans="${trans^}"
        echo "$k=\"${trans}\"" >> "$output_file"
    done
}

label_weather() {
    local weather

    while IFS=':' read -r parameter value ; do

        if [[ "$parameter$value" == "" ]] ; then
            weather+="${NL}"
            continue
        fi

        typeset -u param_uppercase="$parameter"
        label_id="${param_uppercase//[ ]/_}"
        label_value=${!label_id}

        if [ -n "${!label_id+x}" ] ; then
            # shellcheck disable=SC2199
            [[ "${EXCLUDED[@]}" =~ $label_value ]] && label_value="$parameter"
            if [[ "$LANGUAGE_DIRECTION" == "RTL" ]] ; then
                weather+="${RLM}$label_value: ${RLM}${LRM}$value${LRM}${NL}"
            else
                weather+="$label_value: $value${NL}"
            fi
        fi

    done <<< "$1"

    echo "$weather"
}

script_path="${0}"

while [ -L "${script_path}" ] ; do
    path="$(readlink "${script_path}")"
    [[ "${path}" == /* ]] && script_path="$path" || \
        script_path="$(dirname "${script_path}")/${path}"
done

script_dir="$(dirname "${script_path}")"

source "$script_dir/weather-now-menu.conf"
locations_file="$script_dir/locations"
locations_native_file="$script_dir/locations-native"
labels_native_file="$script_dir/labels-native"
conditions_native_file="$script_dir/conditions-native"
last_location_file="$script_dir/last-location"

[[ -e "$locations_file" ]] && source "${locations_file}"

if [[ -n "$1"  ]] ; then
    check_lang "$1"
    rm -f "$last_location_file"
    rm -f "$labels_native_file"
    rm -f "$conditions_native_file"
    LANGUAGE_DIRECTION="LTR"
    if [[ "$1" ==  "en" ]] ; then
        rm -f "$locations_native_file"
    else
        echo "LANGUAGE=\"$1\"" > "$labels_native_file"
        if trans -L "$1" | grep -q "R-to-L" ; then
            LANGUAGE_DIRECTION="RTL"
            echo 'LANGUAGE_DIRECTION="RTL"' >> "$labels_native_file"
        else
            echo 'LANGUAGE_DIRECTION="LTR"' >> "$labels_native_file"
        fi
        coproc progress_dlg { zenity --progress --pulsate \
            --no-cancel --auto-close \
            --title="$TITLE" \
            --text="Translating labels and locations..." ; }
        # translate_labels <labels> <label ids> <lang> <output file> [prefix]
        # where prefix is used to influence translate-shell results
        translate_locations LOCATIONS "$1" "$locations_native_file" "Location: "
        translate_labels LABELS LABEL_IDS "$1" "$labels_native_file" "Command: "
        translate_labels PARAMETER_LABELS PARAMETER_IDS \
            "$1" "$labels_native_file" "Weather: "
        translate_codes CONDITIONS "$1" "$conditions_native_file" "Weather: "
        if [ -n "${EXTRA_PARAMS+x}" ] ; then 
            translate_extra_parameters EXTRA_PARAMS "$1" \
                "$labels_native_file" "Weather: "
        fi
        echo 100  >&"${progress_dlg[1]}"
    fi
fi

[[ -e "$locations_native_file" ]] && source "${locations_native_file}"
[[ -e "$labels_native_file" ]] && source "${labels_native_file}"
[[ -e "$conditions_native_file" ]] && source "${conditions_native_file}"

while true; do

    if [ -n "${last_location+x}" ] ; then
        unset location_data
        unset symbol
        results=""
    fi
    if [[ -f "$last_location_file" ]]; then
        if [[ "$LANGUAGE" == "en" ]] ; then
            IFS=':' read -r placename country_code index \
                < <(cat "$last_location_file")
        else
            IFS=':' read -r placename_native placename country_code index \
                < <(cat "$last_location_file")
        fi
        # shellcheck disable=SC2153
        if [[ " ${LOCATIONS[*]} " =~ ${placename}:${country_code} ]]; then
            if [[ "$LANGUAGE" == en ]] ; then
                location_data+=( "$placename" "$country_code" "$index" )
            else
                location_data+=( "$placename_native" "$placename" \
                    "$country_code" "$index" )
            fi
        fi
    fi

    for (( i=0; i < ${#LOCATIONS[@]}; i++ )); do
        loc="${LOCATIONS[$i]}"
        [[ "$loc" == "$placename:$country_code" ]] && continue
        if [[ "$LANGUAGE" == en ]] ; then
            location_data+=( "${loc%:*}" "${loc#*:}" "$i" )
        else
            location_data+=( "${LOCATIONS_NATIVE[$i]}" \
                "${loc%:*}" "${loc#*:}" "$i" )
        fi
    done

    if [[ "$LANGUAGE_DIRECTION" == "RTL" ]] ; then
        width=600;height=600
    else
        width=500;height=400
    fi

    if [[ "$LANGUAGE" == "en" ]] ; then
        location=$(zenity --list \
            --title="$TITLE" \
            --text="$MENU_TEXT:" \
            --width="$width" \
            --height="$height" \
            --separator=":" \
            --column="$COLUMN_LOCATION" \
            --column="$COLUMN_COUNTRY_CODE" \
            --column="$COLUMN_INDEX" \
            --hide-column=3 \
            --print-column=ALL \
            --cancel-label="${LRM}$MENU_BTN_CANCEL" \
            --ok-label="${LRM}$MENU_BTN_OK" \
            "${location_data[@]}")
    else
        location=$(zenity --list \
            --title="$TITLE" \
            --text="$MENU_TEXT:" \
            --width="$width" \
            --height="$height" \
            --separator=":" \
            --column="$COLUMN_LOCATION_NATIVE" \
            --column="$COLUMN_LOCATION" \
            --column="$COLUMN_COUNTRY_CODE" \
            --column="$COLUMN_INDEX" \
            --hide-column=4 \
            --print-column=ALL \
            --cancel-label="${LRM}$MENU_BTN_CANCEL" \
            --ok-label="${LRM}$MENU_BTN_OK" \
            "${location_data[@]}")
    fi

    [[ -z "$location" ]] && exit 0

    if [[ "$LANGUAGE" == "en" ]] ; then
        IFS=':' read -r placename country_code index < <(echo "$location")
        place="$placename"
    else
        IFS=':' read -r placename_native placename country_code index \
            < <(echo "$location")
        place="$placename_native"
    fi

    if [[ "$CONFIG_NAME" == "simple" ]] ; then
        output_type="simple"
        series=""
    else
        output_type="data-alt"
        series="-s"
    fi

    params_extra="${EXTRA_PARAMS[*]}"
    params_extra=${params_extra// /${NL}}

    while read -r line; do
        k="${line%%:*}"
        v=${line#*: }
        case $k in
        "Conditions")
            code=${v%[*}
            s=${v#*[};description=${s%*]}
            if [[ "$LANGUAGE" == "en" ]] ; then
                results+="$k: $description${NL}"
            else
                results+="$k: ${CONDITIONS_NATIVE["$code"]}${NL}"
            fi ;;
        "Weather symbol" )
            [[ -z "${symbol+x}" ]] && symbol=$v ;;
        *)
            results+="$line${NL}" ;;
        esac
    done < <(exec_command "echo \"$params_extra\" | \"$script_dir/weather_now.py\" \
        -l \"$placename\" -c \"$country_code\" \
        -t \"$TEMPERATURE_UNIT\" -p \"$PRECIPITATION_UNIT\" \
        -w \"$WIND_SPEED_UNIT\" $WIND_IN_DEGREES $series -o \"data-alt\" -")

    if [[ "$LANGUAGE" == "en" ]] ; then
        weather="$results"
    else
        weather=$(label_weather "$(printf "%b" "$results")")
    fi

    if [[ "$output_type" == "simple" ]] ; then
        zenity --forms --title="$TITLE${NL}$place${NL}${NL}$symbol" \
            --text="$weather${PADDING}" --cancel-label="${LRM}$RESULTS_BTN_CANCEL" \
            --ok-label="${LRM}$RESULTS_BTN_OK"
    else
        zenity --text-info --title="$TITLE${NL}$place${NL}${NL}$symbol" \
            --height=800 --width=600 --font="$RESULTS_FONT" \
            --cancel-label="${LRM}$RESULTS_BTN_CANCEL" \
            --ok-label="${LRM}$RESULTS_BTN_OK" <<< "$weather${PADDING}" 
    fi

    exit_code=$?
    last_location="$location"
    echo "$last_location" > "$last_location_file"

    (( exit_code )) && break

done
