#!/bin/bash

# shellcheck disable=SC1090,1091,2034,2129,2154,2329

script_path="${0}"

while [ -L "${script_path}" ] ; do
    path="$(readlink "${script_path}")"
    [[ "${path}" == /* ]] && script_path="$path" || \
        script_path="$(dirname "${script_path}")/${path}"
done

script_dir="$(dirname "${script_path}")"
start="#!\/bin\/bash"
end="script_dir"
script_to_test="$script_dir/../weather-now-menu"
# source globals, functions and setup from script_to_test
source <(sed -n "/$start/,/$end/p" "$script_to_test")
source "$script_dir/../configs/aviation/weather-now-menu.conf"
locations_file="$script_dir/../locations"
locations_native_file="$script_dir/locations-native"
labels_native_file="$script_dir/labels-native"
conditions_native_file="$script_dir/conditions-native"
last_location_file="$script_dir/last-location"

[[ -e "$locations_file" ]] && \
    source "${locations_file}" || LOCATIONS=( Utopia:AU )

# ------------------ function redefines ------------------

unset -f fail_exit
unset -f exec_command
unset -f parse_translation

fail_exit() {
    if [[ "$1" != "unsupported_language" ]] ; then
        SUPPORTED_LANG=0
    fi
    return
}

exec_command() {
    command="$1"
    retry=5
    
    while (( retry )); do
        echo "Executing command:${NL}${NL}${command:0:100}...${NL}" | \
            tee -a "$tests_log_file" 1>&2
        output="$(eval "$command" 2>&1)"
        status=$?
        if [[ -z "${output// }" ]] ; then
            echo "$UNSUPPORTED_MSG" | tee -a "$tests_log_file" 1>&2
            fail_exit "unsupported_language"
            break
        fi
        if (( status )); then
            echo "$output${NL}" | tee -a "$tests_log_file" 1>&2
            echo "Command failed with exit code $status, sleeping 5s..." | \
                tee -a "$tests_log_file" 1>&2
            if (( --retry )) ; then
                sleep 5
                echo "Retrying...${NL}" | tee -a "$tests_log_file" 1>&2
            else
                echo "Giving up and exiting.${NL}" | \
                    tee -a "$tests_log_file" 1>&2
                kill -s TERM $TOP_PID
            fi
        else
            retry=0
            echo "$output"
        fi
    done
}

parse_translation() {
    echo "$1" > "$temp_dir/trans-output.tmp"
    perl -CSD -slne '
        $seps = "\x{002E}\x{003A}\x{02F8}\x{055D}\x{05C3}\x{0903}\x{0F0D}";
        $seps .= "\x{1361}\x{17D6}\x{2024}\x{A789}\x{FE13}\x{FE55}\x{FF1A}$opt_sep";
        $ends = "\x{002E}\x{0964}\x{104B}\x{1362}\x{FF0E}";
        print "$1:$2" while
        /(\d+)[\p{Ps}\s]+[^$seps]+[$seps\s]+([^\p{Pe}$ends]+?)(?=\s*[\p{Pe}$ends]).*?/g' \
            -- -opt_sep="$2" <<< "$1"
}

# ------------------- functions required for tests -------------------

build_langs() {
    mapfile -t LANGS < <(awk -F'|' -v start="$1" -v col="$2" -v pattern="$3" '
        NR>=start && (pattern=="" || $col ~ pattern){
            for(i=2;i<4;i++)gsub(/^[ \t]+|[ \t]+$/,"",$i)
            printf "%s:%s\n" , $2, $3
        }' "docs/$4")
}

validate_native_files() {
    if (grep -icE '(=$|="")' "$labels_native_file" > /dev/null) ; then
        VALIDATION_FAILS+="$1 ($2) - labels-native${NL}"
        return
    fi
    indexes="$(cat "$conditions_native_file" | \
        grep  -ioE '(\[.*\])' - | tr "\n" " ")"
    if [[ "$indexes" != "$CONDITIONS_INDEXES" ]] || \
        (grep -icE '(=$|="")' "$conditions_native_file" > /dev/null) ; then
        VALIDATION_FAILS+="$1 ($2) - conditions-native${NL}"
        return
    fi
}

insert_logging() {
    for ((i=0; i < $2; i++)) ; do  # advance n lines
        read -r line; echo "$line"
    done
    echo "write_to_lang_log \"$1\" \"\$temp_dir/trans-output.tmp\" \"\$lang_log_file\""
}

write_to_lang_log() {
    trans_output="$(cat "$2")"
    if [[ -n "${trans_output// }" ]] ; then
        underline "Analyse $1 at $(date +"%FT%T.%3N")" - >> "$lang_log_file"
        echo "${NL}Parsed translation:${NL}" >> "$lang_log_file"
        parse_translation "$trans_output" >> "$lang_log_file"
        echo "${NL}Raw translation (wrapped):${NL}" >> "$lang_log_file"
        echo "$trans_output" | fmt -w 140 >> "$lang_log_file"
        info="Digits, punctuation and spacing marks found in raw translation:"
        echo "${NL}$info${NL}" >> "$lang_log_file"
        echo "$trans_output" | uni i -f '%cpoint %char %name %cat' | \
            grep -i -E "decimal|\bsign.*\bspacing|other_punctuation" | \
                sort -u -k 2 >> "$lang_log_file"
        echo >> "$lang_log_file"
    else
        SUPPORTED_LANG=0
    fi
}

underline() { 
    echo "$1"; echo "${1//?/$2}"
}

# ---------------- source code from weather-now-menu ----------------

sed_script=$'/rm -f "$last_location_file"/,/echo 100/p'
# wrap it in a function and insert logging commands
test_func="test_lang() {${NL}$(while read -r line  ; do
    case $line in
        *progress_dlg* | --*)
            continue ;;
        translate_locations*)
            echo "$line"
            insert_logging "LOCATIONS" 0 ;;
        translate_labels\ LABELS*)
            echo "$line"
            insert_logging "LABELS" 0 ;;
        translate_labels\ PARAMETER_LABELS*)
            echo "$line"
            insert_logging "PARAMETER_LABELS" 1 ;;
        translate_codes*)
            echo "$line"
            insert_logging "CONDITIONS" 0 ;;
        translate_extra_parameters*)
            echo "$line"
            insert_logging "EXTRA_PARAMS" 2
            echo "fi${NL}}" ;;
        *)
            echo "$line"
    esac
done < <(sed -n "$sed_script" "./weather-now-menu"))"
source <(echo "$test_func")

# -------------------- parse args and run tests ----------------------

(( ! (LANG_TEST % 2) )) && pattern="^[ \t]*🗸[ \t]*$"

if (( LANG_TEST < 2 )) ; then
    ENGINE="google"; start=10; col=4; lang_file="languages-google.md"
else
    ENGINE="bing"; start=15; col=5; lang_file="languages-bing.md"
fi

build_langs "$start" "$col" "$pattern" "$lang_file"
argc=$#

if ! (( argc )) ; then
    tests=( 0 $(( ${#LANGS[@]} - 1 )) )
    argc=2
else
    # shellcheck disable=SC2199
    for (( i=0; i < ${#LANGS[@]}; i++ )) ; do
        code=${LANGS[i]#*:}
        for arg in "$@" ; do
            if [[ "$arg" == "$code" ]] ; then
                tests+=( "$i" )
                (( ${#tests[@]} == argc )) && break 2
            fi
        done
    done
fi

if (( ${#tests[@]} == argc )) ; then
    if (( argc == 2 ))  ; then
        if (( tests[1] >= tests[0] )) ; then
            start=${tests[0]} ; end=${tests[1]}
        else
            start=${tests[1]} ; end=${tests[0]}
        fi
        tests=()
        for (( i=start; i <= end ; i++ )) ; do tests+=( "$i" ) ; done
    fi
    tests_log_dir="$script_dir/logs/"
    tests_log_file="$tests_log_dir/tests.log"
    read -rp "Remove directory '$tests_log_dir' ? [y/N] " answer
    [ "$answer" = y ] && rm -r "$tests_log_dir"
    mkdir -p "$tests_log_dir"
    temp_dir="$(dirname "$(mktemp -u --tmpdir)")"
    CONDITIONS_INDEXES="[0] [1] [2] [3] [45] [48] [51] [53] [55] [56] "
    CONDITIONS_INDEXES+="[57] [61] [63] [65] [66] [67] [71] [73] [75] "
    CONDITIONS_INDEXES+="[77] [80] [81] [82] [85] [86] [95] [96] [99] "
    VALIDATION_FAILS=""
    UNSUPPORTED_LANGS=""
    UNSUPPORTED_MSG="Skipping test - trans returned an empty string. "
    UNSUPPORTED_MSG+="Language is probably unsupported by $ENGINE.${NL}"
    log_header="Starting translation tests    $(date +"%FT%T.%3N")"
    echo "$(underline "$log_header" =)${NL}" > "$tests_log_file"

    for t in "${tests[@]}" ; do
        lang="${LANGS[$t]#*:}"
        lang_name=${LANGS[$t]%:*}
        lang_log_file="$tests_log_dir/$lang.log"
        rm -f "$lang_log_file"
        start_banner="Starting test - $lang_name ($lang)   $(date +"%FT%T.%3N")"
        echo "$(underline "$start_banner" -)${NL}" | \
            tee -a "$tests_log_file" "$lang_log_file"
        SUPPORTED_LANG=1
        test_lang "$lang"
        if (( SUPPORTED_LANG )) ; then
            validate_native_files "$lang_name" "$lang"
            files="$locations_native_file $labels_native_file $conditions_native_file" 
            for f in $files ; do 
                (underline "$(basename "${f}")" -; cat "${f}"; echo) >> "$lang_log_file"
            done
            (( t != tests[${#tests[@]} - 1] )) && sleep 10
        else
            echo "$UNSUPPORTED_MSG" >> "$lang_log_file"
            UNSUPPORTED_LANGS+="$lang_name ($lang)${NL}"
        fi
    done

    end_banner="End of tests    $(date +"%FT%T.%3N")"
    echo "$(underline "$end_banner" -)${NL}" | \
        tee -a "$tests_log_file" "$lang_log_file"
    if [[ "$UNSUPPORTED_LANGS" != "" ]] ; then
        header="The following languages were unsupported by $ENGINE:${NL}"
        echo "$header$UNSUPPORTED_LANGS${NL}" | tee -a "$tests_log_file"
    fi
    if [[ "$VALIDATION_FAILS" != "" ]] ; then
        echo "The following native files were malformed:${NL}$VALIDATION_FAILS" | \
            tee -a "$tests_log_file"
    fi
else
    echo "Invalid language code."
fi