#!/bin/bash

# shellcheck disable=SC1090,1091
# shellcheck disable=SC2329

NL=$'\n'
TAB=$'\t'
# unicode justification markers
LRM=$'\u200E'  # LEFT-TO-RIGHT MARK
RLM=$'\u200F'  # RIGHT-TO-LEFT MARK
WARNING_ICON=$'\u26A0'

# default language
LANGUAGE="en"
LANGUAGE_DIRECTION="LTR"

trap "exit 1" TERM
export TOP_PID=$$

error_exit() {
    cmd_info="${TEXT_CMD_INFO//0/$2}: ${NL}${NL}$1${NL}${NL}"
    output_info="$TEXT_OUTPUT:${NL}${NL}$3"
    
    if zenity --text-info --title="$TITLE${NL}$WARNING_ICON $TEXT_ERROR" \
        --width=600 --height=500 \
        --cancel-label="${LRM}$ERROR_BTN_EXIT" \
        --ok-label="${LRM}$ERROR_BTN_RETRY" \
        2> /dev/null <<< "$cmd_info$output_info" ; then
        echo 1
    else
        kill -s TERM $TOP_PID
        echo 0
    fi
}

fail_exit() {
    zenity --text-info --title="$TITLE${NL}$WARNING_ICON $1" \
        --width=600 --height=500 --cancel-label="" <<< "$2"
    >&2 echo "$1:${NL}${NL}$2"
    kill -s TERM $TOP_PID
}

exec_command() {
    command="$1"
    status=1
    while (( status )); do
        output="$(eval "$command" 2>&1)"
        status=$?
        if (( status )); then
            status=$(error_exit "$command" "$status" "$output")
        else
            echo "$output"
        fi
    done
}

check_lang() {
    codes=$(trans --list-codes)
    for code in $codes ; do
        [[ "$code" == "$1" ]] && return
    done
    err_text="Invalid language code: $1"
    if ! zenity --question --title="$TITLE - Error" \
        --text="$err_text${NL}${NL}Do you wish to continue?" \
        --width=300 --icon="data-warning" --no-markup ; then
        kill -s TERM $TOP_PID
    fi
}

parse_translation() {
    perl -CSD -lne 'my $colons = 
        "\x{003A}\x{02F8}\x{055D}\x{05C3}\x{1361}\x{17D6}\x{A789}\x{FE13}\x{FE55}\x{FF1A}";
        print "$1:$2" while
        /(\d+)[\p{Ps}\s]+.+?[$colons]+\s*(.*?)\s*[\p{P}]+.*?/g' <<< "$1"
}

normalise_digits() {
    perl -CS -MUnicode::UCD=charinfo -pe '
        s/\p{Nd}/charinfo(ord($&))->{numeric}/ge'
}

translate() {
    local trans_input=$1
    local translation
    local lang=$2

    cmd="trans -b -4 -no-warn -e \"$ENGINE\" -4 en:$lang \"$trans_input\""
    translation="$(exec_command "$cmd")"
    if [[ "$translation" == "" ]] ; then
        err_msg1=$'This may be caused by use of an unsupported language code '
        err_msg2=$'Otherwise, it may be due to a temporary translation engine '
        err_msg3=$'or network error. Try restarting weather-now-menu.\n\n'
        err_msg4="Input:${NL}${NL}${trans_input}${NL}${NL}"
        err_msg5="Output:${NL}${NL}${translation}"
        fail_exit "Translation error" \
            "$err_msg1$err_msg2$err_msg3$err_msg4$err_msg5" 
    fi
    parse_translation "$translation"
}

translate_locations() {
    local -n locations=$1
    local lang=$2
    local output_file=$3
    local prefix=$4
    local location
    local trans_input
    local translation

    for ((i=0; i < ${#locations[@]}; i++)); do
        location=${locations[$i]} 
        trans_input+="$i [ $prefix${location%:*} ]. "
    done

    echo "LOCATIONS_NATIVE=(" > "$output_file"

    while IFS=':' read -r index translation ; do
        index=$(normalise_digits <<< "$index")
        echo "${TAB}\"${translation}\"" >> "$output_file"
    done  < <(translate "$trans_input" "$lang")

    echo ")" >> "$output_file"
}

translate_labels() {
    local -n labels=$1
    local -n label_ids=$2
    local lang=$3
    local output_file=$4
    local prefix=$5
    local trans_input
    local translation

    for ((i=0; i < ${#labels[@]}; i++)); do
        trans_input+="$i [ $prefix${labels[$i]} ]. "
    done

    while IFS=':' read -r index translation ; do
        index=$(normalise_digits <<< "$index")
        echo "${label_ids[$index]}=\"$translation\"" >> "$output_file"
    done  < <(translate "$trans_input" "$lang")
}

translate_codes() {
    local lang=$2
    local output_file=$3
    local prefix=$4
    local trans_input

    for (( i=0; i < 100; i++ )) ; do
        if [[ ${CONDITIONS[${i}]} ]] ; then
            trans_input+="$i [ $prefix${CONDITIONS[${i}]} ]. "
        fi
    done

    echo "CONDITIONS_NATIVE=(" > "$output_file"

    while IFS=':' read -r index translation ; do
        index=$(normalise_digits <<< "$index")
        echo "${TAB}[$index]=\"$translation\"" >> "$output_file"
    done < <(translate "$trans_input" "$lang")

    echo ")" >> "$output_file"
}

translate_extra_parameters() {
    local -n params=$1
    local lang=$2
    local output_file=$3
    local prefix=$4
    local trans_input

    for ((i=0; i < ${#params[@]}; i++)); do
        p=${params[$i]}
        p="${p//_/ }"
        p="${p^}"
        trans_input+="$i [ $prefix$p ]. "
    done

    while IFS=':' read -r index translation ; do
        index=$(normalise_digits <<< "$index")
        case "${params[index]}" in
            "cape" )
                k="CAPE"
                translation="$k" ;;
            "total_column_integrated_water_vapour" )
                k="TCWV"
                translation="$k" ;;
            *)
                typeset -u k="${params[index]}"
        esac
        [[ "$LANGUAGE_DIRECTION" == "LTR" ]] && translation="${translation^}"
        echo "$k=\"$translation\"" >> "$output_file"
    done < <(translate "$trans_input" "$lang")
}

label_weather() {
    local weather

    while IFS=':' read -r parameter value ; do

        if [[ "$parameter$value" == "" ]] ; then
            weather+="${NL}"
            continue
        fi

        typeset -u param_uppercase="$parameter"
        label_id="${param_uppercase//[ ]/_}"
        label_value=${!label_id}

        if [ -n "${!label_id+x}" ] ; then
            # shellcheck disable=SC2199
            [[ "${EXCLUDED[@]}" =~ $label_value ]] && label_value="$parameter"
            if [[ "$LANGUAGE_DIRECTION" == "RTL" ]] ; then
                weather+="${RLM}$label_value: ${RLM}${LRM}$value${LRM}${NL}"
            else
                weather+="$label_value: $value${NL}"
            fi
        fi

    done <<< "$1"

    echo "$weather"
}

script_path="${0}"

while [ -L "${script_path}" ] ; do
    path="$(readlink "${script_path}")"
    [[ "${path}" == /* ]] && script_path="$path" || \
        script_path="$(dirname "${script_path}")/${path}"
done

script_dir="$(dirname "${script_path}")"

source "$script_dir/weather-now-menu.conf"
locations_file="$script_dir/locations"
locations_native_file="$script_dir/locations-native"
labels_native_file="$script_dir/labels-native"
conditions_native_file="$script_dir/conditions-native"
last_location_file="$script_dir/last-location"

[[ -e "$locations_file" ]] && source "${locations_file}"

# global definitions, functions and setup from script under test
# ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

# wrap translation logic as a function and
# insert write_to_lang_log calls as required

test_lang() {
    rm -f "$last_location_file"
    rm -f "$labels_native_file"
    rm -f "$conditions_native_file"
    LANGUAGE_DIRECTION="LTR"
    if [[ "$1" ==  "en" ]] ; then
        rm -f "$locations_native_file"
    else
        echo "LANGUAGE=\"$1\"" > "$labels_native_file"
        if trans -L "$1" | grep -q "R-to-L" ; then
            LANGUAGE_DIRECTION="RTL"
            echo 'LANGUAGE_DIRECTION="RTL"' >> "$labels_native_file"
        else
            echo 'LANGUAGE_DIRECTION="LTR"' >> "$labels_native_file"
        fi
        # translate_labels <labels> <label ids> <lang> <output file> [prefix]
        # where prefix is used to influence translate-shell results
        translate_locations LOCATIONS "$1" "$locations_native_file" "Location: "
        write_to_lang_log "LOCATIONS" "$temp_dir/trans-output.tmp" "$lang_log_file"
        translate_labels LABELS LABEL_IDS "$1" "$labels_native_file" "Command: "
        write_to_lang_log "LABELS" "$temp_dir/trans-output.tmp" "$lang_log_file"
        translate_labels PARAMETER_LABELS PARAMETER_IDS \
            "$1" "$labels_native_file" "Weather: "
        write_to_lang_log "PARAMETER_LABELS" "$temp_dir/trans-output.tmp" "$lang_log_file" 
        if [ -n "${EXTRA_PARAMS+x}" ] ; then 
            translate_extra_parameters EXTRA_PARAMS "$1" \
                "$labels_native_file" "Weather: "
        fi
        write_to_lang_log "EXTRA_PARAMS" "$temp_dir/trans-output.tmp" "$lang_log_file" 
        translate_codes CONDITIONS "$1" "$conditions_native_file" "Weather: "
        write_to_lang_log "CONDITIONS" "$temp_dir/trans-output.tmp" "$lang_log_file"
        if (( SUPPORTED_LANG )) ; then
            files="$locations_native_file $labels_native_file $conditions_native_file" 
            for f in $files ; do 
                (underline "$(basename "${f}")" -; cat "${f}"; echo) >> "$lang_log_file"
            done
        fi
    fi
}

# ------------------ function redefines ------------------

unset -f fail_exit
unset -f exec_command
unset -f parse_translation

fail_exit() {
    if [[ "$1" != "unsupported_language" ]] ; then
        SUPPORTED_LANG=0
    fi
    return
}

exec_command() {
    command="$1"
    retry=5
    
    while (( retry )); do
        echo "Executing command:${NL}${NL}${command:0:100}...${NL}" | \
            tee -a "$tests_log_file" 1>&2
        output="$(eval "$command" 2>&1)"
        status=$?
        if [[ "$output" == "" ]] ; then
            echo "$UNSUPPORTED_MSG" | tee -a "$tests_log_file" 1>&2
            fail_exit "unsupported_language"
            break
        fi
        if (( status )); then
            echo "$output${NL}" | tee -a "$tests_log_file" 1>&2
            echo "Command failed with exit code $status, sleeping 5s..." | \
                tee -a "$tests_log_file" 1>&2
            if (( --retry )) ; then
                sleep 5
                echo "Retrying...${NL}" | tee -a "$tests_log_file" 1>&2
            else
                echo "Giving up and exiting.${NL}" | \
                    tee -a "$tests_log_file" 1>&2
                kill -s TERM $TOP_PID
            fi
        else
            retry=0
            echo "$output"
        fi
    done
}

parse_translation() {
    echo "$1" > "$temp_dir/trans-output.tmp"
    perl -CSD -lne 'my $colons = 
        "\x{003A}\x{02F8}\x{055D}\x{05C3}\x{1361}\x{17D6}\x{A789}\x{FE13}\x{FE55}\x{FF1A}";
        print "$1:$2" while
        /(\d+)[\p{Ps}\s]+.+?[$colons]+\s*(.*?)\s*[\p{P}]+.*?/g' <<< "$1"
}

# ------------------- functions required for tests -------------------

validate_native_files() {
    if (grep -icE '(=$|="")' "$labels_native_file" > /dev/null) ; then
        VALIDATION_FAILS+="$1 ($2) - labels-native${NL}"
        return
    fi
    indexes="$(cat "$conditions_native_file" | \
        grep  -ioE '(\[.*\])' - | tr "\n" " ")"
    if [[ "$indexes" != "$CONDITIONS_INDEXES" ]] || \
        (grep -icE '(=$|="")' "$conditions_native_file" > /dev/null) ; then
        VALIDATION_FAILS+="$1 ($2) - conditions-native${NL}"
        return
    fi
}

write_to_lang_log() {
    trans_output="$(cat "$2")"
    if [[ $trans_output != "" ]] ; then
        # shellcheck disable=SC2129
        underline "Analyse $1 at $(date +"%FT%T.%3N")" - >> "$lang_log_file"
        echo "${NL}Parsed translation:${NL}" >> "$lang_log_file"
        parse_translation "$trans_output" >> "$lang_log_file"
        echo "${NL}Raw translatiom:${NL}" >> "$lang_log_file"
        echo "$trans_output" | fmt -w 140 >> "$lang_log_file"
        echo "${NL}Digits and punctuation found in raw translation:${NL}" >> "$lang_log_file"
        echo "$trans_output" | uni i -f '%cpoint %char %name %cat' | \
            grep -i -E "decimal|other_punctuation" | sort -u -k 2 >> "$lang_log_file"
        echo >> "$lang_log_file"
    else
        SUPPORTED_LANG=0
    fi
}

underline() { 
    echo "$1"; echo "${1//?/$2}"
}

# -------------------- parse args and run tests ----------------------

source "$script_dir/langs"
argc=$#

if ! (( argc )) ; then
    tests=( 0 $(( ${#LANGS[@]} - 1 )) )
    argc=2
else
    # shellcheck disable=SC2199
    for (( i=0; i < ${#LANGS[@]}; i++ )) ; do
        code=${LANGS[i]#*:}
        for arg in "$@" ; do
            if [[ "$arg" == "$code" ]] ; then
                tests+=( "$i" )
                (( ${#tests[@]} == argc )) && break 2
            fi
        done
    done
fi

if (( ${#tests[@]} == argc )) ; then
    if (( argc == 2 ))  ; then
        if (( tests[1] >= tests[0] )) ; then
            start=${tests[0]} ; end=${tests[1]}
        else
            start=${tests[1]} ; end=${tests[0]}
        fi
        tests=()
        for (( i=start; i <= end ; i++ )) ; do tests+=( "$i" ) ; done
    fi
    tests_log_dir="$script_dir/logs/"
    tests_log_file="$tests_log_dir/tests.log"
    read -rp "Remove directory '$tests_log_dir' ? [y/N] " answer
    [ "$answer" = y ] && rm -r "$tests_log_dir"
    mkdir -p "$tests_log_dir"
    temp_dir="$(dirname "$(mktemp -u --tmpdir)")"
    CONDITIONS_INDEXES="[0] [1] [2] [3] [45] [48] [51] [53] [55] [56] "
    CONDITIONS_INDEXES+="[57] [61] [63] [65] [66] [67] [71] [73] [75] "
    CONDITIONS_INDEXES+="[77] [80] [81] [82] [85] [86] [95] [96] [99] "
    VALIDATION_FAILS=""
    UNSUPPORTED_LANGS=""
    UNSUPPORTED_MSG="Skipping test - trans returned an empty string. "
    UNSUPPORTED_MSG+="Language is probably unsupported by $ENGINE.${NL}"
    log_header="Starting translation tests    $(date +"%FT%T.%3N")"
    echo "$(underline "$log_header" =)${NL}" > "$tests_log_file"

    for t in "${tests[@]}" ; do
        lang="${LANGS[$t]#*:}"
        lang_name=${LANGS[$t]%:*}
        lang_log_file="$tests_log_dir/$lang.log"
        rm -f "$lang_log_file"
        start_banner="Starting test - $lang_name ($lang)   $(date +"%FT%T.%3N")"
        echo "$(underline "$start_banner" -)${NL}" | \
            tee -a "$tests_log_file" "$lang_log_file"
        SUPPORTED_LANG=1
        test_lang "$lang"
        if (( SUPPORTED_LANG )) ; then
            validate_native_files "$lang_name" "$lang"
            (( t != tests[${#tests[@]} - 1] )) && sleep 10
        else
            echo "$UNSUPPORTED_MSG" >> "$lang_log_file"
            UNSUPPORTED_LANGS+="$lang_name ($lang) - labels-native${NL}"
        fi
    done

    end_banner="End of tests    $(date +"%FT%T.%3N")"
    echo "$(underline "$end_banner" -)${NL}" | \
        tee -a "$tests_log_file" "$lang_log_file"
    if [[ "$UNSUPPORTED_LANGS" != "" ]] ; then
        header="The following languages were unsupported by $ENGINE:${NL}"
        echo "$header$UNSUPPORTED_LANGS${NL}" | tee -a "$tests_log_file"
    fi
    if [[ "$VALIDATION_FAILS" != "" ]] ; then
        echo "The following native files were malformed:${NL}$VALIDATION_FAILS" | \
            tee -a "$tests_log_file"
    fi
else
    echo "Invalid language code."
fi